# Generated by Django 3.0 on 2020-03-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='valid',
            field=models.CharField(default='no', max_length=4),
        ),
        migrations.DeleteModel(
            name='is_valid',
        ),
    ]
