# Generated by Django 3.0 on 2020-03-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200307_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='valid',
            field=models.CharField(default='', max_length=4),
        ),
    ]
