# Generated by Django 3.0 on 2020-03-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='sizef',
            field=models.IntegerField(default=0),
        ),
    ]
